#!/bin/sh

# blow - Copyright (C) 2009  Anthony Green <green@spindazzle.org>
#
# This file is part of BLOW.
#
# BLOW is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 3, or (at your option) any
# later version.
# 
# BLOW is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with BLOW; see the file COPYING3.  If not see
# <http://www.gnu.org/licenses/>. 
# 

# Uncomment this if we want to force BLOWHOME
# BLOWHOME=/usr/share/blow

if test -z $BLOWHOME; then
    BLOWHOME=`dirname $0`;
    BLOWHOME=`(cd $BLOWHOME; pwd)`
fi

GIT=`which git 2>/dev/null`
if test -z $GIT; then
    echo $"ERROR: blow can't find git.  Please install it." 1>&2
    exit 2
fi

if test -z $1; then
    echo $"Usage: $0 PATH" 1>&2
    RETVEL=2
else
    if test -d $1; then
	echo $"ERROR: $1 exists in this directory" 1>&2
	RETVAL=2
    elif test -f $1; then
	echo $"ERROR: $1 exists in this directory" 1>&2
	RETVAL=2
    else
	mkdir -p $1;
	cp -r $BLOWHOME/template/* $1
	RCMD="s|@BLOWHOME@|$BLOWHOME|"
	sed -i -e $RCMD $1/bin/start
	(cd $1; git init; git add *; git commit -m "Project Created")
	RETVAL=$?
    fi
fi

exit $RETVAL
